2 PRINT TAB(33);"HELLO"
4 PRINT TAB(15);"CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY"
6 PRINT: PRINT: PRINT
10 PRINT "HELLO.  MY NAME IS CREATIVE COMPUTER."
20 PRINT: PRINT: N=FUNC(400 (ASK("WHAT'S YOUR NAME? ")))
30 PRINT "HI THERE, ";SHOW(N);", ARE YOU ENJOYING YOURSELF HERE? ";
40 B=ASK(""): PRINT
50 IF COMP(B, "YES")=0 THEN 70
55 IF COMP(B, "NO")=0 THEN 80
60 PRINT SHOW(N);", I DON'T UNDERSTAND YOUR ANSWER OF '";SHOW(B);"'."
65 PRINT "PLEASE ANSWER 'YES' OR 'NO'.  DO YOU LIKE IT HERE";: GOTO 40
70 PRINT "I'M GLAD TO HEAR THAT, ";SHOW(N);".": PRINT
75 GOTO 100
80 PRINT "OH, I'M SORRY TO HEAR THAT, ";SHOW(N);". MAYBE WE CAN"
85 PRINT "BRIGHTEN UP YOUR VISIT A BIT."
100 PRINT
105 PRINT "SAY, ";SHOW(N);", I CAN SOLVE ALL KINDS OF PROBLEMS EXCEPT"
110 PRINT "THOSE DEALING WITH GREECE. YOU DO HAVE PROBLEMS, DON'T YOU?"
120 C=ASK("WHAT KIND (ANSWER SEX, HEALTH, MONEY, OR JOB)? ")
125 PRINT
130 IF COMP(C, "SEX")=0 THEN 200
132 IF COMP(C, "HEALTH")=0 THEN 180
134 IF COMP(C, "MONEY")=0 THEN 160
136 IF COMP(C, "JOB")=0 THEN 145
138 PRINT "OH, ";SHOW(N);", YOUR ANSWER OF ";SHOW(C);" IS GREEK TO ME."
140 GOTO 250
145 PRINT "I CAN SYMPATHIZE WITH YOU ";SHOW(N);".  I HAVE TO WORK"
148 PRINT "VERY LONG HOURS FOR NO PAY -- AND SOME OF MY BOSSES"
150 PRINT "REALLY BEAT ON MY KEYBOARD.  MY ADVICE TO YOU, ";SHOW(N);","
153 PRINT "IS TO OPEN A RETAIL COMPUTER STORE.  IT'S GREAT FUN."
155 GOTO 250
160 PRINT "SORRY, ";SHOW(N);", I'M BROKE TOO.  WHY DON'T YOU SELL"
162 PRINT "ENCYCLOPEADIAS OR MARRY SOMEONE RICH OR STOP EATING"
164 PRINT "SO YOU WON'T NEED SO MUCH MONEY?"
170 GOTO 250
180 PRINT "MY ADVICE TO YOU ";SHOW(N);" IS:"
185 PRINT "     1.  TAKE TWO ASPRIN"
188 PRINT "     2.  DRINK PLENTY OF FLUIDS (ORANGE JUICE, NOT BEER!)"
190 PRINT "     3.  GO TO BED (ALONE)"
195 GOTO 250
200 D=ASK("IS YOUR PROBLEM TOO MUCH OR TOO LITTLE? "): PRINT
210 IF COMP(D, "TOO MUCH")=0 THEN 220
212 IF COMP(D, "TOO LITTLE")=0 THEN 230
215 PRINT "DON'T GET ALL SHOOK, ";SHOW(N);", JUST ANSWER THE QUESTION"
217 D=ASK("WITH 'TOO MUCH' OR 'TOO LITTLE'. WHICH IS IT? "):GOTO 210
220 PRINT "YOU CALL THAT A PROBLEM?!!  I SHOULD HAVE SUCH PROBLEMS!"
225 PRINT "IF IT BOTHERS YOU, ";SHOW(N);", TAKE A COLD SHOWER."
228 GOTO 250
230 PRINT "WHY ARE YOU HERE IN SUFFERN, ";SHOW(N);"?  YOU SHOULD BE"
235 PRINT "IN TOKYO OR NEW YORK OR AMSTERDAM OR SOMEPLACE WITH SOME"
240 PRINT "REAL ACTION."
250 PRINT
255 PRINT "ANY MORE PROBLEMS YOU WANT SOLVED, ";SHOW(N);
260 E=ASK("? "): PRINT
270 IF COMP(E, "YES")=0 THEN 280
273 IF COMP(E, "NO")=0 THEN 300
275 PRINT "JUST A SIMPLE 'YES' OR 'NO' PLEASE, ";SHOW(N);"."
277 GOTO 255
280 GOTO 120
300 PRINT
302 PRINT "THAT WILL BE $5.00 FOR THE ADVICE, ";SHOW(N);"."
305 PRINT "PLEASE LEAVE THE MONEY ON THE TERMINAL."
307 FOR I=1 TO 2000: NEXT I
310 PRINT: PRINT: PRINT
315 G=ASK("DID YOU LEAVE THE MONEY? "): PRINT
325 IF COMP(G, "YES")=0 THEN 350
330 IF COMP(G, "NO")=0 THEN 370
335 PRINT "YOUR ANSWER OF '";SHOW(G);"' CONFUSES ME, ";SHOW(N);"."
340 PRINT "PLEASE RESPOND WITH 'YES' OR 'NO'.": GOTO 315
350 PRINT "HEY, ";SHOW(N);"??? YOU LEFT NO MONEY AT ALL!"
355 PRINT "YOU ARE CHEATING ME OUT OF MY HARD-EARNED LIVING."
360 PRINT:PRINT "WHAT A RIP OFF, ";SHOW(N);"!!!":PRINT
365 GOTO 385
370 PRINT "THAT'S HONEST, ";SHOW(N);", BUT HOW DO YOU EXPECT"
375 PRINT "ME TO GO ON WITH MY PSYCHOLOGY STUDIES IF MY PATIENTS"
380 PRINT "DON'T PAY THEIR BILLS?"
385 PRINT:PRINT "TAKE A WALK, ";SHOW(N);".":PRINT:PRINT:GOTO 999
390 PRINT "NICE MEETING YOU, ";SHOW(N);", HAVE A NICE DAY."
400 PARAM(1) : LOCAL(3): B@=DUP(""): FOR C@=0 TO LEN(A@)-1
410 D@=PEEK(A@, C@): IF (D@ > ORD("a")-1)*(D@ < ORD("z")+1) THEN D@=D@-32
420 B@=JOIN(B@, CHAR(D@)): NEXT: RETURN(B@)
430 REM -- Defining UPPER() is no rocket science ;-)
999 END
