1 PRINT TAB(34);"NAME"
5 PRINT TAB(15);"CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY": PRINT
10 PRINT "HELLO.": PRINT "MY NAME IS CREATIVE COMPUTER."
20 A = ASK("WHAT'S YOUR NAME (FIRST AND LAST): "): L=LEN(A)
30 PRINT: PRINT "THANK YOU, ";
40 FOR I=0 TO L-1: @(I)=PEEK(A,I): NEXT I
50 FOR I=L-1 TO 0 STEP -1: PRINT CHR(@(I));: NEXT I
60 PRINT ".": PRINT "OOPS!  I GUESS I GOT IT BACKWARDS.  A SMART"
70 PRINT "COMPUTER LIKE ME SHOULDN'T MAKE A MISTAKE LIKE THAT!": PRINT
80 PRINT "BUT I JUST NOTICED YOUR LETTERS ARE OUT OF ORDER."
90 PRINT "LET'S PUT THEM IN ORDER LIKE THIS: ";
100 FOR J=1 TO L-1: I=J-1: T=@(J)
110 IF T>@(I) THEN 130
120 @(I+1)=@(I): I=I-1: IF (I=0)+(I>0) THEN 110
130 @(I+1)=T: NEXT J
140 FOR I=0 TO L-1: PRINT CHR(@(I));: NEXT I: PRINT: PRINT
150 D = ASK("DON'T YOU LIKE THAT BETTER? ")
160 IF (COMP("YES",D) + COMP("yes",D)) = 0 THEN 180
170 PRINT: PRINT "I'M SORRY YOU DON'T LIKE IT THAT WAY.": GOTO 200
180 PRINT: PRINT "I KNEW YOU'D AGREE!!"
200 PRINT: PRINT "I REALLY ENJOYED MEETING YOU, ";SHOW(A);"."
210 PRINT "HAVE A NICE DAY!"
999 END

