Print "                      XXXX"
Print "                     X    XX"
Print "                    X  ***  X                XXXXX"
Print "                   X  *****  X            XXX     XX"
Print "                XXXX ******* XXX      XXXX          XX"
Print "              XX   X ******  XXXXXXXXX                XX XXX"
Print "            XX      X ****  X                           X** X"
Print "           X        XX    XX     X                      X***X"
Print "          X         //XXXX       X                      XXXX"
Print "         X         //   X                             XX"
Print "        X         //    X          XXXXXXXXXXXXXXXXXX/"
Print "        X     XXX//    X          X"
Print "        X    X   X     X         X"
Print "        X    X    X    X        X"
Print "         X   X    X    X        X                    XX"
Print "         X    X   X    X        X                 XXX  XX"
Print "          X    XXX      X        X               X  X X  X"
Print "          X             X         X              XX X  XXXX"
Print "           X             X         XXXXXXXX\\     XX   XX  X"
Print "            XX            XX              X     X    X  XX"
Print "              XX            XXXX   XXXXXX/     X     XXXX"
Print "                XXX             XX***         X     X"
Print "                   XXXXXXXXXXXXX *   *       X     X"
Print "                                *---* X     X     X"
Print "                               *-* *   XXX X     X"
Print "                               *- *       XXX   X"
Print "                              *- *X          XXX"
Print "                              *- *X  X          XXX"
Print "                             *- *X    X            XX"
Print "                             *- *XX    X             X"
Print "                            *  *X* X    X             X"
Print "                            *  *X * X    X             X"
Print "                           *  * X**  X   XXXX          X"
Print "                           *  * X**  XX     X          X"
Print "                          *  ** X** X     XX          X"
Print "                          *  **  X*  XXX   X         X"
Print "                         *  **    XX   XXXX       XXX"
Print "                        *  * *      XXXX      X     X"
Print "                       *   * *          X     X     X"
Print "         =======*******   * *           X     X      XXXXXXXX\\"
Print "                *         * *      /XXXXX      XXXXXXXX\\      )"
Print "           =====**********  *     X                     )  \\  )"
Print "             ====*         *     X               \\  \\   )XXXXX"
Print "        =========**********       XXXXXXXXXXXXXXXXXXXXXX"